baseURL = "https://rbino.com"
languageCode = "en-us"
title = "rbino"
theme = "archie"
copyright = "© rbino"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  mode = "auto"
  useCDN = false
  subtitle = "Days since last theme change: 0.<br/>Days since last post: probably more."
  mathjax = true
  katex = true
  favicon = "images/icon512.png"

[[params.social]]
name = "Home"
icon = "home"
url = "/"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/rbino/"

[[params.social]]
name = "Mastodon"
icon = "message-square"
url = "https://patavium.social/@rbino/"

[[params.social]]
name = "SoundCloud"
icon = "music"
url = "https://soundcloud.com/rbino/"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:rbino@gmx.com"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[[menu.main]]
name = "Home"
url = "/"
weight = 10

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 20

[[menu.main]]
name = "About"
url = "/about"
weight = 30

[[menu.main]]
name = "License"
url = "/license"
weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["html", "rss"]
