baseURL = "https://rbino.com"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "rbino"
theme = "hugo-ficurinia"
copyright = "Riccardo Binetti - [License](/license)"

[params]
  author = "Riccardo Binetti"
  description = "Shave all the yaks"

  # It's best to put these icons in the "static" folder of your site
  logo = "/images/logo.svg"
  favicon = "/images/favicon32.png"  # 32x32
  svgicon = "/images/logo.svg"

  fontFamily = "Roboto"
  monoFontSizeMultiplier = 1.15
  contentWidth = "800px"

  enableSearch = false
  enableSidebarLayout = true
  showPostsLink = false
  paperCards = true

[menu]
  [[menu.main]]
    url = "/about"
    name = "About"
    weight = 20

  [[menu.icons]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/rbino"
    weight = 10
  [[menu.icons]]
    identifier = "mastodon"
    name = "Mastodon"
    url = "https://patavium.social/@rbino"
    weight = 20
  [[menu.icons]]
    identifier = "soundcloud"
    name = "SoundCloud"
    url = "https://soundcloud.com/rbino"
    weight = 30
  [[menu.icons]]
    identifier = "email"
    name = "Email"
    url = "mailto:rbino@gmx.com"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
    home = ["html", "json", "rss"]
