baseURL = "https://rbino.com"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "rbino"
theme = "diary"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true

[params]
author = "Riccardo Binetti"
subtitle = "Shave all the yaks"
keywords = "blog,developer,personal"
description = "rbino's Personal Blog"
favicon = "images/favicon32.png"
enableOpenGraph = true
enableTwitterCards = true
disableToC = true

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
url = "/about"
name = "About"
weight = 20
[[menu.main]]
url = "/license"
name = "License"
weight = 30
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 40
