baseurl = "https://rbino.com"
title = "rbino"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsStyle = "monokai"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[params]
    author = "Riccardo Binetti"
    info = "Software developer"
    description = "rbino's website"
    keywords = "blog,developer,personal"
    avatarurl = "images/rbino-avatar.jpg"

    favicon_16 = "images/favicon16.png"
    favicon_32 = "images/favicon32.png"

    hidecredits = true
    hidecopyright = false
    since = 2019

    colorScheme = "dark"
    hidecolorschemetoggle = false

    rtl = false

    math = true
    customCSS = ["css/custom.css"]

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/rbino/"
[[params.social]]
    name = "Soundcloud"
    icon = "fa fa-soundcloud fa-2x"
    weight = 2
    url = "https://soundcloud.com/rbino"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/errebino/"
[[params.social]]
    name = "Medium"
    icon = "fa fa-medium fa-2x"
    weight = 4
    url = "https://medium.com/@rbino/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about"

[[menu.main]]
    name = "License"
    weight = 2
    url = "/license"
