baseURL = "https://rbino.com"
languageCode = "en-us"
title = "rbino"
theme = "archie"
copyright = "© rbino"

pygmentsstyle = "gruvbox"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsOptions = "linenos=inline"

[params]
  mode = "auto"
  useCDN = false
  subtitle = "Happily shaving yaks"
  mathjax = false
  katex = false
  favicon = "/images/icon512.png"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/rbino/"

[[params.social]]
name = "Bluesky"
icon = "message-square"
url = "https://bsky.app/profile/rbino.com"

[[params.social]]
name = "SoundCloud"
icon = "music"
url = "https://soundcloud.com/rbino/"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:rbino@gmx.com"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[[menu.main]]
name = "About"
url = "/about"
weight = 20

[[menu.main]]
name = "Talks"
url = "/talks"
weight = 30

[[menu.main]]
name = "License"
url = "/license"
weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["html", "rss"]
